In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
# import all necessory libraries
import pandas as pd
import numpy as np

###### *All Credit goes to Data Science Lovers youtube channel for providing dataset and asking wonderful questions. Please find the links for the same below:*
https://youtube.com/playlist?list=PLy3lFw0OTlutzXFVwttrtaRGEEyLEdnpy

## **1.Weather Dataset**

Q. 1)  Find all the unique 'Wind Speed' values in the data.  
Q. 2) Find the number of times when the 'Weather is exactly Clear'.  
Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'.  
Q. 4) Find out all the Null Values in the data.    
Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.  
Q. 6) What is the mean 'Visibility' ?  
Q. 7) What is the Standard Deviation of 'Pressure'  in this data?  
Q. 8) What is the Variance of 'Relative Humidity' in this data ?  
Q. 9) Find all instances when 'Snow' was recorded.  
Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'.  
Q. 11) What is the Mean value of each column against each 'Weather Condition ?  
Q. 12) What is the Minimum & Maximum value of each column against each 'Weather Condition ?  
Q. 13) Show all the Records where Weather Condition is Fog.  
Q. 14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.  
Q. 15) Find all instances when :  
A. 'Weather is Clear' and 'Relative Humidity is greater than 50'  
or  
B. 'Visibility is above 40'

In [3]:
# Let's load Weather Data dataset
Weather_df = pd.read_csv('/content/drive/My Drive/Data_Science/Material_DS/Pandas/Weather Data.csv')

In [4]:
# lets check the dimensions and information about the dataset
Weather_df.shape

(8784, 8)

In [5]:
Weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [6]:
Weather_df.head()

       Date/Time  Temp_C  ...  Press_kPa               Weather
0  1/1/2012 0:00    -1.8  ...     101.24                   Fog
1  1/1/2012 1:00    -1.8  ...     101.24                   Fog
2  1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3  1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4  1/1/2012 4:00    -1.5  ...     101.23                   Fog

[5 rows x 8 columns]

In [7]:
Weather_df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

##### **Q. 1) Find all the unique 'Wind Speed' values in the data.**

In [8]:
Weather_df['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

##### **Q. 2) Find the number of times when the 'Weather is exactly Clear'.**

In [9]:
# Lets check the unique values from Weather column
Weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [10]:
Weather_df[Weather_df['Weather']== 'Clear'].shape[0]

1326

##### **Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'.**

In [11]:
wind_4km_h =  Weather_df[Weather_df['Wind Speed_km/h']== 4 ].shape[0]
print('The wind speed exactly 4Km/h is {} times.'.format(wind_4km_h))

The wind speed exactly 4Km/h is 474 times.

##### **Q. 4) Find out all the Null Values in the data.**

In [12]:
Weather_df.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

**There are no missing values in the dataset.**

##### **Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.**

In [14]:
Weather_df.rename(columns = {"Weather":'Weather Condition'}, inplace=True)
Weather_df.head()

       Date/Time  Temp_C  ...  Press_kPa     Weather Condition
0  1/1/2012 0:00    -1.8  ...     101.24                   Fog
1  1/1/2012 1:00    -1.8  ...     101.24                   Fog
2  1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3  1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4  1/1/2012 4:00    -1.5  ...     101.23                   Fog

[5 rows x 8 columns]

##### **Q. 6) What is the mean 'Visibility' ?**

In [17]:
round(Weather_df["Visibility_km"].mean(),2)

27.66

##### **Q. 7) What is the Standard Deviation of 'Pressure' in this data?**

In [18]:
Weather_df["Press_kPa"].std()

0.8440047459486474

## **2.Cars data**

Q. 1) Instruction ( For Data Cleaning ) - Find all Null Values in the dataset. If there is any null value in any column, then fill it with the mean of that column.
Q. 2) Question ( Based on Value Counts )- Check what are the different types of Make are there in our dataset. And, what is the count (occurrence) of each Make in the data ?
Q. 3) Instruction ( Filtering ) - Show all the records where Origin is Asia or Europe.
Q. 4) Instruction ( Removing unwanted records ) - Remove all the records (rows) where Weight is above 4000.
Q. 5) Instruction ( Applying function on a column ) - Increase all the values of 'MPG_City' column by 3.

## **3. Police Data**

Q. 1) Instruction ( For Data Cleaning ) - Remove the column that only contains missing values.
Q. 2) Question ( Based on Filtering + Value Counts ) - For Speeding , were Men or Women stopped more often ? 
Q. 3) Question ( Groupby ) - Does gender affect who gets searched during a stop ?
Question ( mapping + data-type casting )
Q. 4) Question ( mapping + data-type casting ) - What is the mean stop_duration ?
Q. 5) Question ( Groupby , Describe ) - Compare the age distributions for each violation.

## **4. covid_19_data**

Q. 1) Show the number of Confirmed, Deaths and Recovered cases in each Region.
Q. 2) Remove all the records where the Confirmed Cases is Less Than 10.
Q. 3) In which Region, maximum number of Confirmed cases were recorded ?
Q. 4) In which Region, minimum number of Deaths cases were recorded ?
Q. 5) How many Confirmed, Deaths & Recovered cases were reported from India till 29 April 2020 ?
Q. 6-A ) Sort the entire data wrt No. of Confirmed cases in ascending order.
Q. 6-B ) Sort the entire data wrt No. of Recovered cases in descending order.

## **5. London Housing Data**

Q. 1) Convert the Datatype of 'Date' column to Date-Time format.
Q. 2) Add a new column ''year'' in the dataframe, which contains years only.(B.2) Add a new column ''month'' as 2nd column in the dataframe, which contains month only.
Q. 3) Remove the columns 'year' and 'month' from the dataframe.
Q. 4) Show all the records where 'No. of Crimes' is 0. And, how many such records are there ?
Q. 5) What is the maximum & minimum 'average_price' per year in england ?
Q. 6) What is the Maximum & Minimum No. of Crimes recorded per area ?
Q. 7) Show the total count of records of each area, where average price is less than 100000.

## **6. India Census 2011**

Q. 1) How will you hide the indexes of the dataframe.
Q. 2) How can we set the caption / heading on the dataframe.
Q. 3) Show the records related with the districts - New Delhi , Lucknow , Jaipur.
Q. 4) Calculate state-wise :
A. Total number of population.
B. Total no. of the population with different religions.
Q. 5) How many Male Workers were there in Maharashtra state ?
Q. 6) How to set a column as index of the dataframe ?
Q. 7a) Add a Suffix to the column names.
Q. 7b) Add a Prefix to the column names.

## **7. Udemy Courses**

Q. 1) What are all different subjects for which Udemy is offering courses ?
Q. 2) Which subject has the maximum number of courses.
Q. 3) Show all the courses which are Free of Cost.
Q. 4) Show all the courses which are Paid.
Q. 5) Which are Top Selling Courses ?
Q. 6) Which are Least Selling Courses ?
Q. 7) Show all courses of Graphic Design where the price is below 100 ?
Q. 8) List out all the courses that are related to 'Python'.
Q. 9) What are courses that were published in the year 2015 ?
Q. 10) What is the Max. Number of Subscribers for Each Level of courses ?

## **8. Netflix Dataset**

Task. 1) Is there any Duplicate Record in this dataset ? If yes, then remove the duplicate records.
Task. 2) Is there any Null Value present in any column ? Show with Heat-map.
Q. 1) For 'House of Cards', what is the Show Id and Who is the Director of this show ?
Q. 2) In which year the highest number of the TV Shows & Movies were released ? Show with Bar Graph.
Q. 3) How many Movies & TV Shows are in the dataset ? Show with Bar Graph.
Q. 4) Show all the Movies that were released in year 2000.
Q. 5) Show only the Titles of all TV Shows that were released in India only.
Q. 6) Show Top 10 Directors, who gave the highest number of TV Shows & Movies to Netflix ?
Q. 7) Show all the Records, where "Category is Movie and Type is Comedies" or "Country is United Kingdom".
Q. 8) In how many movies/shows, Tom Cruise was cast ?
Q. 9) What are the different Ratings defined by Netflix ?
Q. 9.1) How many Movies got the 'TV-14' rating, in Canada ?
Q. 9.2) How many TV Shows got the 'R' rating, after year 2018 ?
Q. 10) What is the maximum duration of a Movie/Show on Netflix ?
Q. 11) Which individual country has the Highest No. of TV Shows ?
Q. 12) How can we sort the dataset by Year ?
Q. 13) Find all the instances where: Category is 'Movie' and Type is 'Dramas' or Category is 'TV Show' & Type is 'Kids' TV'.